### ISSUE TITLE
Duplicate user (user can create multiple accout with same details).

### ISSUE THREAD

**Issue by Krishnapro** [Krishnapro/notescollab#7]
**Describe the bug**
Users can create multiple accounts with the same details like same username or emailid or all the details will be same.

**Expected behavior**
Before saving/creating the new user make sure to check and verify in the database there is no account/ user whose `username` and `email` match with the current user. If there is already a user with the same username and email throw the message  - `"user already exit with same username/email"`

**Comment by Krishnapro** [comment]
Hi @mennafabio you can start working. Are you clear about the issue?

**Comment by mennafabio** [comment]
Hey @Krishnapro , yes im clear about the issue. I created a PR for this issue https://github.com/Krishnapro/notescollab/pull/8
